Update README.md
argoproj-labs/argo-cloudops pull request #213
Opened 2021-12-07 17:40 UTC by ysmolyar

2021-12-07 17:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj-labs/argo-cloudops?pullRequest=213) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj-labs/argo-cloudops?pullRequest=213) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj-labs/argo-cloudops?pullRequest=213) it.</sub>

2021-12-08 01:00 UTC, pclata approved these changes

2021-12-08 22:14 UTC, thbishop-intuit requested changes

2021-12-08 22:14 UTC, thbishop-intuit commented on examples/README.md
> +This directory contains examples of application being defined as code in
```suggestion
This directory contains examples of an application being defined as code in
```

2021-12-14 00:09 UTC, thbishop-intuit approved these changes

2021-12-14 00:09 UTC, merged